### ISSUE TITLE
CTRL+Space in China 

### ISSUE THREAD

**Issue by inuxor** [moson-mo/pacseek#1]
> To install/remove a package, press CTRL+Space.

CTRL+Space is default to change IME in Chinese 
so I ( and most of Chinese input method user ) can't install / uninstall any package in pacseek

why not just use ENTER to install / uninstall a focused package

**Comment by moson-mo** [comment]
Thanks for the info.

At some point I had ENTER used for fetching the package details (which now happens automatically when you move through the package list).

I'll have a look to change that.
