### ISSUE TITLE
backspace isn't working on xterm.

### ISSUE THREAD

**Issue by moson-mo** [moson-mo/pacseek#10]
One more thing: backspace isn't working on xterm.

_Originally posted by @leo-arch in https://github.com/moson-mo/pacseek/issues/9#issuecomment-1192881697_

**Comment by AladW** [comment]
I can confirm this issue

**Comment by moson-mo** [comment]
me too :)

**Comment by moson-mo** [comment]
Ok, found it.

CTRL+H is used to display the help/instructions.
Now xterm seems to that for "Backspace" https://wiki.archlinux.org/title/Xterm#Fix_the_backspace_key

I should probably change that to CTRL+I or so...

**Comment by leo-arch** [comment]
Nice find! Maybe you could experiment a bit with `xterm` escape codes (most of which are understood by most terminals): they allow you to (un)set features that normally are set via a dedicated file (`.Xresources`). If a escape code exists to fix the backspace issue, you can use it in `pacseek` code itself without the need to change the original keybind or messing up with user config files.

See https://www.xfree86.org/current/ctlseqs.html

I use this escape codes to handle some features of the terminal, for example, cursor position on the screen, `Alt` keybindings, and a few more things. Quite interesting reading.

**Comment by moson-mo** [comment]
fixed with https://github.com/moson-mo/pacseek/commit/77123beb1a16547c29d62680a912b93d6eddda3e / https://github.com/moson-mo/pacseek/commit/a048300bdc462c8881606086a78a2beb7526803a
