### ISSUE TITLE
Sorting options and filters

### ISSUE THREAD

**Issue by StarTroop** [moson-mo/pacseek#11]
This is perhaps beyond the scope of the project, but I would like to request some QoL features:

1. Keybinds for dynamically re-sorting the listed packages alphabetically (more useful when searching with 'Contains'), according to last modified date, or according to popularity (official packages on top), in ascending and descending orders.
2. Keybinds to dynamically filter listed packages by installed status (yes or no) and by source. It would also be nice to have a quick option to include or exclude only the AUR (i.e. group all proper repos together instead of manually selecting each one), which should also apply to the "-r" command line option.
3. Filter packages even further by inputting terms to be matched with dependencies or conflicts. Not as important, but could be handy.

Bonus request: Show Out of Date flags in package list and date flagged in description.

**Comment by moson-mo** [comment]
Hello @StarTroop 

1. Sorting possibilities were added. See [wiki entry](https://github.com/moson-mo/pacseek/wiki/Usage#sorting)
2. The sorting options for "Installed" and "Source" should be good enough to replace a filtering function.
3. At the moment I don't consider implementing that.

Bonus: Out of date is only available for AUR packages. While "packages.archlinux.org" does have a flagging mechanism as well, this data is not contained in the package DB's.
Nevertheless, the "Flagged out of date" field has been added to the package details and will be shown for all AUR packages that have been flagged.

**Comment by StarTroop** [comment]
Thank you! I'm happy with your implementations, and this has already surpassed pamac as the most convenient way to search the databases!
