### ISSUE TITLE
Error starting pacseek:  character set not supported

### ISSUE THREAD

**Issue by nwg-piotr** [moson-mo/pacseek#13]
I use pacseek on two other machines w/o any problem. Now I'm on vacation with only my old testing laptop, that runs Arch Linux installed with the `archinstall` script. The `pacseek` command returns as in the title:

```text
$ pacseek
Error starting pacseek:

character set not supported
```
When started with `LC_ALL=C pacseek` it starts, but looks like this:

![image](https://user-images.githubusercontent.com/20579136/184508127-a023d71c-c770-45b7-9fe3-704cb263bd0f.png)

I use Polish locale `pl_PL.UTF-8`.

**Comment by moson-mo** [comment]
Hmm, that message comes from [tcell](https://github.com/gdamore/tcell/) I guess.

I can start it with `LANG=pl_PL.UTF-8 pacseek` just fine though.
Which terminal emulator are you using?

Could you post the output of some commands:
```shell
locale -a
locale
cat /etc/locale.conf
echo $TERM
```
When you run it with `LANG=C.UTF-8 pacseek` it should be looking ok I guess?

**Comment by nwg-piotr** [comment]
```text
$ locale -a
C
C.UTF-8
en_US.utf8
pl_PL.utf8utf8
POSIX
[piotr@asus ~]$ locale
LANG=pl_PL.UTF-8.UTF-8
LC_CTYPE="pl_PL.UTF-8.UTF-8"
LC_NUMERIC="pl_PL.UTF-8.UTF-8"
LC_TIME="pl_PL.UTF-8.UTF-8"
LC_COLLATE="pl_PL.UTF-8.UTF-8"
LC_MONETARY="pl_PL.UTF-8.UTF-8"
LC_MESSAGES="pl_PL.UTF-8.UTF-8"
LC_PAPER="pl_PL.UTF-8.UTF-8"
LC_NAME="pl_PL.UTF-8.UTF-8"
LC_ADDRESS="pl_PL.UTF-8.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8.UTF-8"
LC_ALL=
[piotr@asus ~]$ cat /etc/locale.conf
LANG=pl_PL.UTF-8.UTF-8
[piotr@asus ~]$ echo $TERM
foot
```
> When you run it with LANG=C.UTF-8 pacseek it should be looking ok I guess?

Yes, it's all right.

**Comment by moson-mo** [comment]
> $ cat /etc/locale.conf
LANG=pl_PL.UTF-8.UTF-8

You have UTF-8 two times there...  
Should be: `LANG=pl_PL.UTF-8`

Also maybe check `/etc/locale.gen`  
It should be `pl_PL.UTF-8 UTF-8` (space instead of .)

**Comment by nwg-piotr** [comment]
All the locale configuration has been done by the `archinstall` script, so maybe a bug on their side? I fixed manually, and pacseek starts. Thank you for your help.

**Comment by moson-mo** [comment]
> a bug on their side?

Yeah, seems so: https://github.com/archlinux/archinstall/issues/1401
