### ISSUE TITLE
PKGBUILDs not shown when chaotic-aur repo is enabled

### ISSUE THREAD

**Issue by Mudskipper875** [moson-mo/pacseek#14]
### Steps to reproduce
1. Enable chaotic-aur repo
2. Search with pacseek for an AUR package which is also available in the choatic-aur
3. Try to view PKGBUILD of AUR package (shows _404: Not Found_ error)
- This does not happen for AUR packages which are not in the chaotic-aur.

![](https://user-images.githubusercontent.com/89634034/188500517-b5a270d6-2bc4-46dc-8c08-cb15c7ef92c5.png)

(This may be relevant: A similar problem exists with **yay** when the chaotic-aur is enabled.
Running `yay -Gp informant` will not show the PKGBUILD and shows an error.
This could be fixed by running either `yay -Gpa informant` or `yay -Gp aur/informant`)

**Comment by moson-mo** [comment]
Hello @Mudskipper875 
The new [1.6.6](https://github.com/moson-mo/pacseek/releases/tag/v1.6.6) version should fix this issue.
Please give it a try...

**Comment by Mudskipper875** [comment]
It works now, Thanks!
