### ISSUE TITLE
Add background settings to entire window

### ISSUE THREAD

**Issue by ajgringo619** [moson-mo/pacseek#21]
After changing `SettingsFieldBackground` to `000000` in `colors.json`, my news items background now appears as my normal XFCE terminal text does - transparent. Is this available for the rest of the window? If not, can it be added?

Here's an example of what I'm talking about:
![pacseek](https://user-images.githubusercontent.com/53413561/193368330-c74191b8-ba9a-4a44-9cd2-69232c750ed0.jpg)

**Comment by moson-mo** [comment]
That background color for news items is a glitch actually.
It has nothing to do with the "SettingsFieldBackground" value though.

I might add some "Transparent" option at some point. However, this most likely requires a lot of changes and testing.

**Comment by moson-mo** [comment]
Implemented in v1.7.3

**Comment by ajgringo619** [comment]
Absolutely perfect - thanks so much!
