### ISSUE TITLE
Unable to use search terms with leading hyphens from the command-line

### ISSUE THREAD

**Issue by Mudskipper875** [moson-mo/pacseek#23]
Using pacseek v1.7.3
#### Steps to reproduce
`pacseek -s '-icon-theme'`
or
`pacseek -- '-icon-theme'`
#### Current behavior
Error: `flag not supported: icontheme`

#### Steps to reproduce
`pacseek -s -m`
#### Current behavior
Opens pacseek with the monochrome (`-m`) option applied, but also searches for packages with '-m' as the search term.

### Possible Solutions
1. Don't parse the argument after `-s` as a command-line option.
2. Add support for double-dash (`--`) to mark the end of the command-line options. e.g. `pacseek -m -- -icon-theme`.

**Comment by moson-mo** [comment]
Should be fine with the last commit.
I'll make a new release soon...
