### ISSUE TITLE
Error while searching for AUR packages

### ISSUE THREAD

**Issue by zer0exia** [moson-mo/pacseek#24]
Didn't have any problem searching packages using yay or paru, but searches used with pacseek produce error and empty result ;

`Error : Get https://server.moson.rocks/rpc?v=5&type=seach&by=name&arg=pacseek" : context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by moson-mo** [comment]
Can't reproduce that issue. Maybe a network hiccup or so.

**Comment by zer0exia** [comment]
Found the problem, it happens if I am connected to Cloudflare Warp. Yay or paru isn't affected, so I'm not entirely sure if this problem is on warp side. Any logs or debug output that I should provide?

**Comment by moson-mo** [comment]
> Cloudflare Warp

Don't know how that works.  
What's your "AUR timeout" setting? Try to increase it a bit.

**Comment by moson-mo** [comment]
Hmm. No clue why they would block that one.  
I host an [own instance](https://github.com/moson-mo/goaurrpc) instance of /rpc for pacseek so there is less requests on the AUR itself. (It's fine if you change that though).

**Comment by zer0exia** [comment]
Okay I figured as much. I think we can close this one as this issue isn't on pacseek. Though I wanna ask, if I'm using the official aur address, would there be a risk of something like Pamac ddos incident to occur? Using an own instance like you did in this case probably already mitigate it

**Comment by moson-mo** [comment]
> would there be a risk of something like Pamac ddos incident to occur?

No, don't worry. The AUR handles over a million requests per day. A couple more shouldn't harm :wink:

**Comment by somepaulo** [comment]
> t's solved after I tried changing the 'AurRpcUrl'

Saved me!

**Comment by somepaulo** [comment]
> I host an [own instance](https://github.com/moson-mo/goaurrpc)

Your host might be blocking connections from Surfshark IPs. Happens occasionally with different hosts and different Surfshark locations.
