### ISSUE TITLE
Weird discoloration with certain values of ${TERM}

### ISSUE THREAD

**Issue by DJSigmann** [moson-mo/pacseek#25]
I use alacritty as my terminal emulator (https://github.com/alacritty/alacritty) and use the `alacritty-direct` terminfo entry as described in `extras/alacritty.info`.

When I run pacseek it takes several seconds to load and then displays the interface with a very strange, dulled look:
`$ pacseek`
![2023-01-08_12-26](https://user-images.githubusercontent.com/26459936/211193658-5fd31e79-edca-4e55-80a7-6a4e43646dcd.png)

It loads near-instantly and appears normal if I change the Value of $TERM:
`$ TERM=xterm-direct pacseek`
![2023-01-08_12-30](https://user-images.githubusercontent.com/26459936/211193815-0d8e1032-fc5e-4f45-a2e2-83938153d3fd.png)

If I replace the `xterm-direct` terminfo entry with the `alacritty-direct` entry:
`$ infocmp alacritty-direct | perl -np -e "s/alacritty/xterm/g;" | sudo tic -x -`

and then run for a second time:
`$ TERM=xterm-direct pacseek`

Pacseek works just as it should.

And if I do the opposite and replace the `alacritty-direct` terminfo entry with the `xterm-direct` entry it still behaves oddly.
In fact, from my testing, it seems that any value for `$TERM`  is alright as long as it doesn't include `-direct` unless it is `xterm-direct`; the content of the relevant terminfo entry seems to be irrelevant.

I have managed to reproduce this behaviour in several terminal emulators:
- Alacritty
- St
- Xterm

I suspect this may be some sort of bug, perhaps 'xterm-direct' was hard coded somewhere.

**Comment by moson-mo** [comment]
That slow loading glitch was corrected in tcell it seems. https://github.com/gdamore/tcell/commit/7557ac2a6c896c346fd600f715d5357f48667925
Updating dependencies fixes that. I'll have to see if I file a new release for this.

Not sure what the issue with those colors is though.  
It probably needs a definition for `alacritty-direct` similar to the xterm one.
F.e.: https://github.com/gdamore/tcell/blob/main/terminfo/x/xterm/direct.go

**Comment by moson-mo** [comment]
Fixed for `alacritty-direct`.
Now there seems to be some general issue of handling the `-direct` term variants with terminfo atm.
https://github.com/gdamore/tcell/pull/585#issuecomment-1378162180
