### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by RannyBergamotte** [moson-mo/pacseek#28]
Maybe stupid and out of scope, but if flatpak is installed, pacseek should be able to install flatpaks from flathub. That would be such a cool feature, and would make pacseek the ultimate package/software store. Some things are only available in flatpaks.

**Comment by RannyBergamotte** [comment]
Just wanted to also say, absolutely love pacseek, use it all the time! Having it all in a simple easy to use and read tui is so much nicer then any gui application for installing packages while removing the pain of doing it by hand or by the command line. Truly thank you for this!

**Comment by moson-mo** [comment]
Thanks.  
Sorry, atm, I don't have any plans to add flatpak support.

**Comment by CavaleriOmar** [comment]
> Maybe stupid and out of scope, but if flatpak is installed, pacseek should be able to install flatpaks from flathub. That would be such a cool feature, and would make pacseek the ultimate package/software store. Some things are only available in flatpaks.

It's not an official integration, but anyway you can handle the automatic update of flatpak packages by editing the command that pacseek uses to update (which I had to do anyway, using garuda), adding
`&& flatpak update`

**Comment by revast** [comment]
there is now [flatpak-cli](https://github.com/sweetbbak/flatpak-cli), which seems to have the same goal, though not directy based on fzf: 

"A command line program to search and install flatpaks from the flathub repo using a fzf like interface. "
