### ISSUE TITLE
Text selection by mouse

### ISSUE THREAD

**Issue by Ashark** [moson-mo/pacseek#32]
Hello.

Thank you, this is really a cool project. I just accidentally saw it in the Brodie Robertson video. Bad that I did not know about it before.

How can I select the text with my mouse? For example, I want to copy paste someone's PKGBUILD or just copy the package name. When I try doing that, nothing happens.

**Comment by killajoe** [comment]
depending more on what your terminal emulator offers ;)

**Comment by Ashark** [comment]
I am using Yakuake - Konsole in KDE.

**Comment by killajoe** [comment]
hmmm seems not possible no clue if it was like that before.. 
@moson-mo should tell ;)

**Comment by Ashark** [comment]
I have noticed that when I hold Shift, then I can select kinda. But the whole horizontal line is selected, without taking the panel into account.

**Comment by killajoe** [comment]
seems to be by design and yea same here this is working holding shift cursor changed to copy mode..

**Comment by moson-mo** [comment]
Offering mouse support as well text selection is somewhat tricky.
There is actually a feature request here: https://github.com/rivo/tview/issues/774

If you have the need to copy content from the PKGBUILD, you can switch to an external program for displaying.
See https://github.com/moson-mo/pacseek/wiki/Configuration#show-pkgbuild-internally
