### ISSUE TITLE
Specify Repo

### ISSUE THREAD

**Issue by aidan-gibson** [moson-mo/pacseek#33]
For example, currently, if you `pacseek speedtest++` and also have the chaotic-aur prioritized in your `/etc/pacman.conf`, and you select the AUR version of speedtest++ and hit enter, it will install the chaotic-aur version anyway. The workaround, of course, is exiting pacseek and using `yay -S aur/speedtest++`. But this is unexpected behavior within pacseek and should be fixed, I think.

Thanks for the program! Love this thing.

**Comment by moson-mo** [comment]
v1.8.3 should allow you to customize your command like for example: `yay -S {repo}/{pkg}`
(More info: https://github.com/moson-mo/pacseek/wiki/Configuration#install-command)

**Comment by aidan-gibson** [comment]
Perfect thank you that solves the issue! I would seriously consider making this default if it isn't already. Thanks again!
