### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by zxck1l** [moson-mo/pacseek#35]
My problem:
```
pacseek                                                                                                                                                                            
pacseek: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory
```
I use arch linux, can you help me?

**Comment by Ved-un** [comment]
@moson-mo needs to update the package    
Pacman has been updated and now has libalpm.so.15    
    
In the meantime, you can temporarily install the pacseek-git package    
https://aur.archlinux.org/packages/pacseek-git

**Comment by somepaulo** [comment]
`pacman` got updated to v7.0.0 and libalpm to v15, so `libalpm.so.14` is no longer available. Pacseek needs to be updated to work with the new version of `libalpm`.

**Comment by somepaulo** [comment]
> Hello!

You should really change the title of your issue to  something like 'Not working with new version of libalpm'.

**Comment by moson-mo** [comment]
as mentioned by @somepaulo, just rebuild and reinstall the package.
