### ISSUE TITLE
configuration only makes sense with pacman wrappers

### ISSUE THREAD

**Issue by AladW** [moson-mo/pacseek#4]
The current install, upgrade commands assume a pacman wrapper that handles both AUR and repository packages. This limits the usefulness to people who choose not to use pacman wrappers. An alternative would be:

* AUR install command
* AUR upgrade command
* install command
* upgrade command

**Comment by AladW** [comment]
Yes, but then I can't install or upgrade AUR packages from the interface (or even view them, if the AUR lookup is disabled?), which seems useful.

Note that additional AUR install/upgrade commands in the configuration could default to the value of the install/upgrade commands, when left blank. That way there's no redundancy for users of pacman wrappers.

**Comment by moson-mo** [comment]
Yes, right. I'm actually assuming that an AUR helper is being used which delegates the installation to pacman in case of a repo package. Like yay or paru does.

But I see your point, in case an AUR helper is not being used you'd need separate methods/commands to handle both cases.
I'll think about it. I'll try to keep things as simple as possible, but your suggestion makes sense.

For the install command, there would be a workaround though by just calling a shell-script which evaluates the output of something like `pacman -Ss "^$1\$"` to determine if the package is available in a repo and then use different commands to handle the installation.

**Comment by moson-mo** [comment]
I've added some config options for separate commands.

![image](https://user-images.githubusercontent.com/13588013/162235580-eaeee39f-cd2d-4555-9d19-2d051181a48b.png)

![image](https://user-images.githubusercontent.com/13588013/162235842-f950c346-e20f-4a85-a2e6-2cd751811b31.png)

If a package originates from the AUR and "Use separate commands for AUR packages" is enabled, it'll execute the respective commands. The input fields in settings are only visible when that option is enabled.

**Comment by AladW** [comment]
Perfect, thanks for the quick follow-up.

**Comment by AladW** [comment]
Yes, but then I can't install or upgrade AUR packages from the interface (or even view them, if the AUR lookup is disabled?), which seems useful.

Note that additional AUR install/upgrade commands in the configuration could default to the value of the install/upgrade commands, when left blank. That way there's no redundancy for users of pacman wrappers.

On Wed, 06 Apr 2022 11:47:24 -0700
moson-mo ***@***.***> wrote:

> Hi @AladW 
> 
> Thanks for the feedback.
> 
> > The current install, upgrade commands assume a pacman wrapper that handles both AUR and repository packages.
> 
> That is correct assuming you use the default settings.
> 
> You can disable the AUR lookup and replace the install / remove / update command in the settings with e.g. `sudo pacman -S`, etc...
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/moson-mo/pacseek/issues/4#issuecomment-1090616009
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>


-- 
alad ***@***.***>
