### ISSUE TITLE
Make default search to contains instead of startwith

### ISSUE THREAD

**Issue by MiyeonLin** [moson-mo/pacseek#5]
This would make end user experience much better, especially those who are new to linux, my cousin who was used to using pamac was suggested by me to use this, he had trouble searching for packages cause he was used to pamac's method of searching with contain. I know this can be changed easily through the setting but a gui program should be simplified for new users & i think this is one of the changes needed. If its just me thinking this, just ignore my suggestion. Thank you for making such an amazing replacement to pamac.

**Comment by moson-mo** [comment]
Hi @MiyeonLin 

Thanks for your feedback.

Actually the main reason is pretty much to not stress the server too much.
Those API calls are way less resource intensive than the contains search.

I'll think about it though. I see that it might be confusing for first time users.

**Comment by moson-mo** [comment]
I changed the default to "Contains" now.

Note that this app does not try to replace pamac or any other package manager.
The main goal is just to allow searching (and hopefully finding :rofl: ) packages from the terminal.
The install / upgrade / removal task is left to more capable applications. :wink:

I'm glad you like it though.
