### ISSUE TITLE
display in light terminal theme

### ISSUE THREAD

**Issue by inuxor** [moson-mo/pacseek#6]
![Screenshot_20220414_170632](https://user-images.githubusercontent.com/1345457/163357465-bf276f1e-d711-4572-aa23-5920c899ddf5.png)
seems not fully covered the background

**Comment by moson-mo** [comment]
Hi @inuxor 

Thanks for your feedback.

I see the issue with the header bar in the package list and the source column.

![image](https://user-images.githubusercontent.com/13588013/163362570-0d032e30-f87c-4efa-b301-26c6be63b690.png)

Will be fixed soon.

However for those white boxes, no clue what is causing that.
It seems you are using a non-monospace font in some of the screenshots. That won't work properly I guess.
