### ISSUE TITLE
cannot open URLs

### ISSUE THREAD

**Issue by CouldBeThis** [moson-mo/pacseek#7]
Hello I think this is great. :)

One feedback. It is not possible to open the URL for the package which is displayed in the right pane. 

In kitty, xfce terminal and konsole:

- hover over URL = 
  - line appears under URL indicating it is being recognized by terminal emulator
  - cursor changes from regular arrow to pointing hand (except in konsole this doesn't happen)
 - click URL = no action
 - right click URL = no action
 - click & drag = unable to select URL to copy/paste to browser
 - shift + (drag) click = *can* select text this way. but if the URL is too long and gets wrapped, would have to pick out the text from box drawing and left column

In terminator,  it is as above *execpt* if you *double* right click the context menu pops up and it is possible to select "Open link", which works

In alacrity, the URL doesn't get picked up at all. No underline, no cursor change. Can use shift + (drag) click as above.

I verified in kitty, alacritty and terminator that I was able to interact with URLs are expected in another TUI application (gitui) so I believe the issue isn't in my system.

**Comment by moson-mo** [comment]
Most terminals detect URL's and it should work with CTRL + Click (in xfce4-terminal, terminator this works)
In kitty it works with Shift + Click.

There are a couple of issues about that topic at the github repository of `tview`(which is used in pacseek for the tui stuff).
Like https://github.com/rivo/tview/issues/108

Now there is also this commit https://github.com/gdamore/tcell/commit/e7b14a71dc78721c0f007fd6197262c52c1d4df9 in tcell (which in turn is used by tview) to address hyperlinks. However, at the moment tview imports an earlier version of tcell where it is not present.

I might give it a try and fork tview and update the modules to see if I can make use of the new Url thing from tcell.
That being said, I'm not sure if want to go down that rabbit hole though. There might be good reasons that tview did not yet adopt to the latest tcell version...

Regarding alacritty there is also this: https://github.com/alacritty/alacritty/issues/922
So, I'm not even sure if that would fix it there.

**Comment by CouldBeThis** [comment]
Idk if this would be just too hacky. But if the URL would be made to span the whole terminal window instead of half, it would be a lot easier to copy properly. Because being on 2 lines is what turns the selected URL into something like ` https://github.com/moson-        │║║│                              ││               mo/pacseek`

I think that part could be a lot improved by a keyboard shortcut that would toggle horizontal instead of vertical split. Which would sometimes be useful in other situations like when there is really long package names. 

Wouldn't really solve the URL issue but work around more easily.

**Comment by moson-mo** [comment]
This might help:

https://github.com/moson-mo/pacseek/wiki/Usage#resizing-components

**Comment by moson-mo** [comment]
I've solved it differently. With [1.3.2](https://github.com/moson-mo/pacseek/releases/tag/v1.3.2), when you click on a URL it will execute `xdg-open` which should open your default browser and navigate to the page.
(make sure you have `xdg-utils` installed...)

This should also fix the problem with the line-wrapping where the URL is split into multiple lines...

**Comment by CouldBeThis** [comment]
it works! :D
