### ISSUE TITLE
[REQUEST] Toggle which repos to search

### ISSUE THREAD

**Issue by BrodieRobertson** [moson-mo/pacseek#8]
I know you can disable the AUR searching but what would be really useful is to extend that to other sources as well, maybe I just want to search for packages in extra, or community, etc.

I'm not sure on the best approach but maybe a list of repos to search in the config and then in application an interactable list where you can toggle what you want to be using on the fly.

**Comment by moson-mo** [comment]
Not sure how much value this would add.
As an end-user I pretty much always want to search all repositories (and I don't really care where it comes from) 🤷🏻‍♂️ 
Now if I already know that a certain package is contained in `core`, I would probably not even want to use the search at all.

The only case in which it would make sense I guess is if you already know that something is residing in a certain repo.
E.g. searching for "linux" to find all available kernels. There it could make sense to limit to `core` only to limit the list of results.
My feeling is those cases are rather exceptional though.

Maybe a command line option would make sense for these cases:

Some examples:
`pacseek linux -repo core` (immediately search for "linux", limit to `core` repo)
`pacseek -repo core` (limit to `core`repo)
`pacseek -repo extra,community` (limit to `extra` and `community` repo)

**Comment by BrodieRobertson** [comment]
A launch option seems like the simplest approach, you're right that having it in the config might confuse the user
