### ISSUE TITLE
Issues with non-unicode terminal emulators

### ISSUE THREAD

**Issue by leo-arch** [moson-mo/pacseek#9]
Hey @moson-mo, great job! I like it.

However, `pacseek` is barely usable on non-unicode terminal emulators, like `xterm`, `rxvt`, and so on.

Would it it be possible to add a `-i, --ascii` or `--no-unicode` switch to use ASCII instead of Unicode chars to draw borders and decorations?

Thank you very much in advance.

**Comment by moson-mo** [comment]
Hi @leo-arch,
thanks for your feedback. I wasn't aware non-unicode is still a thing ;)

The lib I'm using is indeed [using UTF-8 chars](https://github.com/rivo/tview/issues/57) for the borders it seems.

What I could probably do, is to add an option to disable borders altogether.
Which would look something like this:

![image](https://user-images.githubusercontent.com/13588013/180410850-ef8859ec-48c0-4888-92ab-e15edef7e087.png)

Still not ideal, but better than nothing I guess?

**Comment by AladW** [comment]
xterm fully supports unicode, and even fontconfig. So if this doesn't work with xterm, it's likely a misconfiguration.

Case-in-point: https://imgur.com/2TRznAa.png

**Comment by moson-mo** [comment]
@leo-arch: I've added an option for "ASCII mode" (-i). Could you give it a try with latest commit?

**Comment by leo-arch** [comment]
> xterm fully supports unicode

@AladW, you're right. I should have said non-unicode terms/fonts, or even better, non-unicode setups. In my case, the issue isn't due to a misconfig, but rather to the fact that I choose to use non-unicode bitmap fonts, since they better fit my needs.

**Comment by leo-arch** [comment]
@moson-mo, that was quick! Thanks. I'll take a look at it right now.

**Comment by moson-mo** [comment]
> @moson-mo, that was quick! Thanks. I'll take a look at it right now.
> 
> EDIT: Works as expected. Closing.

Nice. I'll make a new release soon.
Thanks

**Comment by leo-arch** [comment]
I don't think it's related to the ASCII thing. It's rather a theme (color scheme) issue. What I normally do is to test my software on the most basic terminals (even kernel console) to ensure the sanest defaults and the maximum compatibility, specially regarding the interface, which is the first thing a user sees (and of course you don't want a user to dismiss/uninstall your program just because a minor issue).

Briefly said, what I'd do is to set saner default colors. Black on white (if you want some contrast), or white on black, is by far the most compatible color combination (though not the only possibility of course).

And, if you want to go further, customizable color schemes would be even better. But that's another story.

**Comment by leo-arch** [comment]
One more thing: backspace isn't working on xterm.

**Comment by moson-mo** [comment]
> What I normally do is to test my software on the most basic terminals (even kernel console) to ensure the sanest defaults and the maximum compatibility, specially regarding the interface, which is the first thing a user sees (and of course you don't want a user to dismiss/uninstall your program just because a minor issue).

I just try to be compatible with "mainstream terminal emulators" in this case to be honest. I don't really want to sacrifice features for compatibility at some point. But I'm always open for changes to get things working for everyone (like this case)

> Briefly said, what I'd do is to set saner default colors.

Hey, most of the blueish is the Arch Linux color #1793d1. There is nothing saner than that 😉

**Comment by leo-arch** [comment]
> I just try to be compatible with "mainstream terminal emulators" in this case to be honest. I don't really want to sacrifice features for compatibility at some point. But I'm always open for changes to get things working for everyone (like this case)

And I fully respect that! Software design is about making decisions, and decisions always come at a price.

> Hey, most of the blueish is the Arch Linux color #1793d1. There is nothing saner than that

Simply true.

**Comment by moson-mo** [comment]
FYI: I've changed ASCII mode flag from `-i` to `-a`.
`-i` is now used to show all installed packages on startup.

https://github.com/moson-mo/pacseek/commit/6c87ac39809595a21064509ac3ca3af881a3519d
